### ISSUE TITLE
ChatGLM3适配问题

### ISSUE THREAD

**Issue by zhiqix** [JacksonWuxs/Interpret_Instruction_Tuning_LLMs#1]
吴博好，我在将Generator中的input_explain方法进行ChatGLM3-6B模型适配时，遇到如下问题：回传中所有层的梯度都正常，但到input_embed时梯度出现了大部分是0的情况，不知您之前是否遇到类似的问题。
<img width="644" alt="image" src="https://github.com/JacksonWuxs/Interpret_Instruction_Tuning_LLMs/assets/74062817/418d308d-441b-47bb-80fb-ece984526251">

**Comment by JacksonWuxs** [comment]
嗨你好zhiqi，

您提及的现象我在适配llama/mistral/gpt-2这类decoder-only的自回归模型没有遇到过。由于我没太接触过GLM的代码，所以我可能没办法给出最直接的建议。但基于我对于GLM有限的理解，我可能会考虑是否和GLM的masking策略有关。

祝好，
吴烜圣
